# Generated by Django 6.0.3 on 2026-03-19 20:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('snowflake', 'Snowflake'), ('tableau', 'Tableau'), ('database', 'Database'), ('api', 'API'), ('file', 'File'), ('other', 'Other')], default='other', max_length=50)),
                ('connector', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('formula', models.TextField(blank=True)),
                ('data_type', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('trust_level', models.CharField(choices=[('verified', 'Verified (90-100%)'), ('high', 'High (75-89%)'), ('medium', 'Medium (60-74%)'), ('low', 'Low (40-59%)'), ('untrusted', 'Untrusted (0-39%)')], max_length=20)),
                ('completeness_score', models.FloatField(default=0.0)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('timeliness_score', models.FloatField(default=0.0)),
                ('validity_score', models.FloatField(default=0.0)),
                ('uniqueness_score', models.FloatField(default=0.0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_scores', to='core.datasource')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_rules', models.IntegerField(default=0)),
                ('passed_rules', models.IntegerField(default=0)),
                ('failed_rules', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.datasource')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
