# Generated by Django 6.0.3 on 2026-03-19 22:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governancemetric',
            name='formula',
            field=models.TextField(blank=True, help_text='Canonical calculation formula (e.g. SUM(amount) WHERE status=completed)'),
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('consistent', 'Consistent'), ('divergent', 'Divergent'), ('partial', 'Partially Consistent')], default='consistent', max_length=20)),
                ('total_sources', models.IntegerField(default=0)),
                ('consistent_sources', models.IntegerField(default=0)),
                ('divergent_sources', models.IntegerField(default=0)),
                ('consistency_score', models.FloatField(default=0.0, help_text='Percentage of sources with consistent definitions', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('divergences', models.JSONField(blank=True, default=list, help_text='List of specific divergences found')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Suggested actions to resolve divergences')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('governance_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='core.governancemetric')),
                ('sources_compared', models.ManyToManyField(related_name='reconciliations', to='core.datasource')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='DataLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('etl', 'ETL Pipeline'), ('replication', 'Replication'), ('api_sync', 'API Sync'), ('manual', 'Manual'), ('streaming', 'Streaming')], default='etl', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.CharField(blank=True, help_text='e.g. hourly, daily, real-time', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metrics_transferred', models.ManyToManyField(blank=True, related_name='lineage_flows', to='core.governancemetric')),
                ('source_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_outgoing', to='core.datasource')),
                ('source_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_incoming', to='core.datasource')),
            ],
            options={
                'ordering': ['source_from__name'],
                'unique_together': {('source_from', 'source_to', 'flow_type')},
            },
        ),
        migrations.CreateModel(
            name='SemanticDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_type', models.CharField(choices=[('metric', 'Metric'), ('dimension', 'Dimension'), ('relationship', 'Relationship')], default='metric', max_length=20)),
                ('local_name', models.CharField(help_text='Name of this metric/field in the source system (e.g. "total_rev" in Snowflake)', max_length=200)),
                ('local_formula', models.TextField(blank=True, help_text='How this metric is calculated in this specific source')),
                ('local_description', models.TextField(blank=True, help_text='How this source describes/defines the metric')),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='Maps canonical column names to source-specific column names')),
                ('filters', models.JSONField(blank=True, default=list, help_text='Filters applied in this source (e.g. WHERE status=active)')),
                ('is_consistent', models.BooleanField(default=True, help_text='Whether this definition is consistent with the canonical governance metric')),
                ('consistency_notes', models.TextField(blank=True, help_text='Notes on any inconsistencies found')),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('governance_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_definitions', to='core.governancemetric')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_definitions', to='core.datasource')),
            ],
            options={
                'ordering': ['governance_metric__name', 'source__name'],
                'unique_together': {('governance_metric', 'source')},
            },
        ),
    ]
