# Generated by Django 6.1.2 on 2026-10-08 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_governancemetric_formula_reconciliationrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationrun',
            name='run_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trustscore',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='validationresult',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
