# Generated by Django 6.1.2 on 2026-10-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timestamps_default_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('snowflake', 'Snowflake'), ('tableau', 'Tableau'), ('database', 'Database'), ('api', 'API'), ('file', 'File'), ('dbt', 'dbt'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
